name: Deploy to Free Hosting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: |
          backend/package-lock.json
          frontend/package-lock.json
    
    - name: Install backend dependencies
      run: |
        cd backend
        npm ci
    
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Lint backend
      run: |
        cd backend
        npm run lint
    
    - name: Lint frontend
      run: |
        cd frontend
        npm run lint
    
    - name: Build backend
      run: |
        cd backend
        npm run build
    
    - name: Build frontend
      run: |
        cd frontend
        npm run build

  deploy-preview:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy Preview
      run: |
        echo "🚀 Deploy preview would happen here"
        echo "Preview deployments can be set up with Vercel/Netlify GitHub integration"
    
  deploy-production:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy Production
      run: |
        echo "🎉 Production deployment would happen here"
        echo "Production deployments are handled by:"
        echo "- Railway (auto-deploys from main branch)"
        echo "- Vercel (auto-deploys from main branch)"
        echo "- Render (auto-deploys from main branch)"
